#!/usr/bin/python

import os
import platform

Import('env')

lib_name = 'http'

src_dir = Dir('.').abspath
#===============================================================================
sources = [
            Glob(os.path.join(src_dir, 'src', '*.cpp')),
          ]

libs = [
         'boost_system',
         'boost_thread',
         'boost_regex',
         'boost_context',
         'boost_coroutine',
         'cityhash',
         'http_parser',
         'aux',
       ]
       
local_env = env.Clone()
if not platform.platform().startswith('Darwin'):
    libs.append(['tcmalloc'])
    local_env['CCFLAGS'].append(['-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free'])

#===============================================================================
# Build
http_lib = local_env.SharedLibrary(lib_name, sources, LIBS = libs)
local_env.Install(os.path.join(env['STAGE_DIR'], 'lib'), http_lib)


SConscript(['test/sconscript'])
