#!/usr/bin/python

import os
import platform

Import('env')


src_dir = Dir('.').abspath


libs = [
         #'boost_regex',
         'boost_system',
         #'boost_thread',
         #'boost_random',
         #'boost_filesystem',
         #'boost_date_time',
         #'boost_coroutine',
         'gomp',
         'gtest',
         #'http',
         'aux',
         #'evolution',
         'cityhash',
         'pthread',
       ]


local_env = env.Clone()
#===============================================================================
# Uncomment the line below to enable Boost.Asio debug logging of async events
#local_env['CCFLAGS'].append(['-DBOOST_ASIO_ENABLE_HANDLER_TRACKING', '-Wno-unused-variable', '-Wno-unused-result']);
#===============================================================================
if not platform.platform().startswith('Darwin'):
    libs.append(['tcmalloc'])
    local_env['CCFLAGS'].append(['-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free'])


#==================================== Build ===========================================
quant_test = local_env.Program('quant-test', ['quant-test.cpp'], LIBS = libs)
local_env.Install(os.path.join(env['STAGE_DIR'], 'bin'), quant_test)

