#!/usr/bin/python

import os
import platform

Import('env')


src_dir = Dir('.').abspath


libs = [
         #'boost_regex',
         'boost_system',
         #'boost_thread',
         #'boost_random',
         #'boost_filesystem',
         #'boost_date_time',
         #'boost_coroutine',
         #'pthread',
         #'sqldb',
         'gtest',
         'pthread',
         'cityhash',
         'aux',
       ]


local_env = env.Clone()
if not platform.platform().startswith('Darwin'):
    libs.append(['tcmalloc'])
    local_env['CCFLAGS'].append(['-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free'])



#==================================== Build ===========================================
aux_test = local_env.Program('aux-test', ['aux-test.cpp'], LIBS = libs)
local_env.Install(os.path.join(env['STAGE_DIR'], 'bin'), aux_test)

